# -*- coding: utf-8 -*-
"""mini_string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12x5t3jp3x-htKpdcnxlwLQME4tsprn1p
"""

print("1. Name Formatter")
print("2. Email Validator")
print("3. Word Counter")
print("4. Palindrome Checker")

choice = input("Choose an option (1-4): ")

if choice == "1":
    name = input("Enter your name: ")
    print(name.title())

elif choice == "2":
    email = input("Enter email: ")

    if (
        email.count("@") == 1
        and "." in email
        and " " not in email
    ):
        print("Valid Email")
    else:
        print("Invalid Email")

elif choice == "3":
    text = input("Enter text: ")

    print("Words:", len(text.split()))
    print("Characters:", len(text))

elif choice == "4":
    word = input("Enter a word: ").lower()

    if word == word[::-1]:
        print("Palindrome")
    else:
        print("Not Palindrome")

else:
    print("Invalid Choice")